# Generated by Django 4.1.1 on 2023-08-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_profile',
        ),
    ]
