# Generated by Django 4.1.1 on 2023-01-27 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time_of_comment',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
