# Generated by Django 4.1.1 on 2023-01-27 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comments_time_of_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_of_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
