# Generated by Django 4.1.1 on 2023-08-03 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_follow_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
