# Generated by Django 4.1.1 on 2023-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='profile_pics/default image.jpg', upload_to='profile_pics'),
        ),
    ]
