# Generated by Django 4.1.1 on 2023-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_profile_pics',
            field=models.ImageField(default='static/defaultimage.jpg', upload_to='bg_profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='static/defaultimage2.jpg', upload_to='profile_pics'),
        ),
    ]
