# Generated by Django 4.1.1 on 2023-03-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_background_profile_pics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_profile_pics',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pics',
        ),
        migrations.CreateModel(
            name='User_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(default='profile_pics/defaultimage2.jpg', upload_to='profile_pics')),
                ('background_profile_pics', models.ImageField(default='background_profile_pics/defaultimage2.jpg', upload_to='background_profile_pics')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
