# Generated by Django 4.1.1 on 2023-03-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_background_profile_pics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_images',
            options={'verbose_name_plural': 'User_images'},
        ),
        migrations.AlterField(
            model_name='user_images',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
