# Generated by Django 4.1.1 on 2023-03-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_images_options_alter_user_images_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_images',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
