# Generated by Django 4.1.1 on 2023-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_background_profile_pics_profile_profile_pics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='profile_img')),
                ('background_img', models.ImageField(upload_to='background_img')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_profile_pics',
            field=models.ImageField(upload_to='bg_profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
