# Generated by Django 4.1.1 on 2023-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_defaultimage_alter_profile_background_profile_pics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_profile_pics',
            field=models.ImageField(default='bg_profile_pics/defaultimage.jpg', upload_to='bg_profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pics',
            field=models.ImageField(default='profile_pics/defaultimage2.jpg', upload_to='profile_pics'),
        ),
    ]
