# Generated by Django 4.1.1 on 2023-03-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_background_profile_pics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultImage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='core.likepost'),
        ),
    ]
