# Generated by Django 4.1.1 on 2023-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
