# Generated by Django 4.1.1 on 2023-03-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.OneToOneField(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='core.likepost'),
        ),
    ]
