# Generated by Django 4.1.1 on 2023-03-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_likepost_post_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
