# Generated by Django 4.1.1 on 2023-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_likepost_post_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=True, to='core.likepost'),
        ),
    ]
