# Generated by Django 4.1.1 on 2023-03-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='username',
            new_name='liked_by',
        ),
    ]
