# Generated by Django 4.1.1 on 2023-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_of_likes',
        ),
    ]
