# Generated by Django 4.1.1 on 2023-03-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_post_num_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
