# Generated by Django 4.1.1 on 2023-03-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_country_continent_follow_user_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_object',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.follow'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.follow'),
        ),
    ]
