# Generated by Django 4.1.1 on 2023-03-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_follow_user_object_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
