# Generated by Django 4.1.1 on 2023-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_profile_city_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
